name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build sln
      run: dotnet build -c Release --no-cache /clp:NoSummary ./HappyCode.NetCoreBoilerplate.sln
      
    #- name: Test with TRX file
    #  run: dotnet test -c Release --no-build --filter FullyQualifiedName!~LoadTests --logger "trx;LogFileName=TestResults.trx" ./HappyCode.NetCoreBoilerplate.sln
    
    - name: Test with Xunit XML file
      run: dotnet test -c Release --no-build --logger "xunit;LogFileName=TestResults.xml" --filter FullyQualifiedName!~LoadTests /maxcpucount:1 /p:WarningLevel=0 ./HappyCode.NetCoreBoilerplate.sln
      
    #- name: Archive test results
     # uses: actions/upload-artifact@v2
      #if: success() || failure()
      #with:
       # name: Artifact for TRX files
        #path: test/**/TestResults.trx
        
    - name: Archive test results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: Artifact for Xunit XML files
        path: test/**/TestResults.xml
        
      
