name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:      
  collect-trx-test-results:
      name: Create Artifact for TRX test results
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

      - name: Test with TRX file
        run: dotnet test --logger "trx;LogFileName=TestResults.trx" --filter FullyQualifiedName!~LoadTests /maxcpucount:1 /p:WarningLevel=0 ./HappyCode.NetCoreBoilerplate.sln
      - name: Archive test results for TRX files
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-result-trx
          path: test/**/TestResults.trx
        
        
  collect-xunit-test-results:
      name: Create Artifact for Xunit XML test results
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

    
      - name: Test with Xunit XML file
        run: dotnet test --logger "xunit;LogFileName=TestResults.xml" --filter FullyQualifiedName!~LoadTests /maxcpucount:1 /p:WarningLevel=0 ./HappyCode.NetCoreBoilerplate.sln
      
      - name: Archive test results for Xunit XML files
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: Artifact for Xunit XML files
          path: test/**/TestResults.xml
        
      
